
version: '3.3'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"