#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

if [[ $STAGED_GO_FILES != "" ]]; then
    for file in $STAGED_GO_FILES; do
        go fmt $file
        git add $file
    done
fi

NORMAL=$(tput sgr0)
MAGENTA=$(tput setaf 5)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

printf "${MAGENTA}Running go test${NORMAL}\n"
go test
if [[ $? != 0 ]]; then
  printf "${RED}Test failed! ${NORMAL}Please fix errors before committing.\n"
  exit 1
else
 printf "${GREEN}Test passed! ${NORMAL}Continuing to commit.\n"
fi

GOLANGCI_LINT=$GOPATH/bin/golangci-lint

# Check for golangci-lint
if [[ ! -x "$GOLANGCI_LINT" ]]; then
  printf "\t\033[41mPlease install golangci-lint (go get -u github.com/golangci/golangci-lint/cmd/golangci-lint)"
  exit 1
fi


printf "${MAGENTA}Running golangci-lint${NORMAL}\n"

golangci-lint run
if [[ $? != 0 ]]; then
  printf "${RED}Linting failed! ${NORMAL}Please fix errors before committing.\n"
  exit 1
else
 printf "${GREEN}Linting passed! ${NORMAL}Continuing to commit.\n"
fi

