name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-central-1

  HANDLER_IMAGE: dyleme/handler
  CONV_IMAGE: dyleme/converter

  ECS_HANDLER_SERVICE: image-converter-handler
  ECS_CONV_SERVICE: image-converter-convert
  ECS_CLUSTER: dziauho-image-convesion

  ECS_HANDLER_TASK_DEFINITION: .aws/handler-task-definition.json 
  ECS_CONV_TASK_DEFINITION: .aws/conv-task-definition.json 

  HANDLER_CONTAINER_NAME: image-converter-handler
  CONV_CONTAINER_NAME: image-converter-convert

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for handler Docker
      id: handler_meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.HANDLER_IMAGE }} 

    - name: Build and push Docker handler image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./Dockerfile.conv
        push: true
        tags: ${{ steps.handler_meta.outputs.tags }}
        labels: ${{ steps.handler_meta.outputs.labels }}

    - name: Extract metadata (tags, labels) for converter Docker
      id: conv_meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.CONV_IMAGE }} 

    - name: Build and push Docker converter image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: ./Dockerfile.conv
        push: true
        tags: ${{ steps.conv_meta.outputs.tags }}
        labels: ${{ steps.conv_meta.outputs.labels }}


    - name: Fill in the new handler image ID in the Amazon ECS task definition
      id: handler-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_HANDLER_TASK_DEFINITION }}
        container-name: ${{ env.HANDLER_CONTAINER_NAME }}
        image: ${{ env.HANDLER_IMAGE }}

    - name: Fill in the new conv image ID in the Amazon ECS task definition
      id: conv-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_CONV_TASK_DEFINITION }}
        container-name: ${{ env.CONV_CONTAINER_NAME }}
        image: ${{ env.CONV_IMAGE }}

    - name: Deploy Amazon ECS handler task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.handler-task-def.outputs.task-definition }}
        service: ${{ env.ECS_HANDLER_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Amazon ECS conv task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.conv-task-def.outputs.task-definition }}
        service: ${{ env.ECS_CONV_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true