name: test_lint

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test.full
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: latest
        skip-go-installation: true
